run:
  issues-exit-code: 0

issues:
  max-issues-per-linter: 1000
  max-same-issues: 1000

output:
  format: checkstyle

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - depguard
    - dogsled
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - prealloc
    # - stylecheck
    - unconvert
    - unparam
    # - whitespace
    - wsl

linters-settings:
  errcheck:
    ignore: "[rR]ead|[w|W]rite|[c|C]lose|[c|C]ommit|[r|R]ollback|[p|P]rintln"

  goconst:
    min-len: 5

  golint:
    min-confidence: 1.0
